INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('abcedaw', '1346dl', 'jun', 'j005580@naver.com')
INSERT INTO USER (USER_ID, PASSWORD, NAME, EMAIL) VALUES ('admin', '1234', 'jun', 'j005580@naver.com')
